-
  branches:
    only:
      - master
  configuration: Release
  artifacts:
    - path: '**\LitmosApi.*.nupkg' # find all NuGet packages recursively
      name: MyApp
  deploy:
    provider: NuGet
    api_key:
      secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
    skip_symbols: false
    artifact: MyApp
  os: Visual Studio 2017
  install:
    - choco install gitversion.portable -pre -y
  assembly_info:
    patch: false
  build:
    project: LitmosApi\LitmosApi.csproj
  before_build:
    - dotnet restore
    - ps: .\build.ps1
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
-
  configuration: Debug
  os: Visual Studio 2017
  version: 1.0.{build}
  build:
    project: LitmosApi\LitmosApi.csproj
  before_build:
    - dotnet restore
    - ps: .\build.ps1
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
