-
  branches:
    only:
      - master
  configuration: Release
  artifacts:
    - path: '**\LitmosApi.*.nupkg' # find all NuGet packages recursively
      name: MyApp
  deploy:
    provider: NuGet
    api_key:
      secure: pd9kF0t0Bt6BExgB0t6xEQT9pAlFrRhFZDl6LDGTZjtgaI4nd4ilIongUFWZKLOO
    skip_symbols: false
    artifact: MyApp
  os: Visual Studio 2017
  install:
    - choco install gitversion.portable -pre -y
  assembly_info:
    patch: false
#  after_build:
#    - cmd: ECHO nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#    - cmd: nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#    - cmd: appveyor PushArtifact "<NuSpec>.%GitVersion_NuGetVersion%.nupkg"    
  build:
    project: LitmosApi\LitmosApi.csproj
  before_build:
    - dotnet restore
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
-
  configuration: Debug
  os: Visual Studio 2017
  version: 1.0.{build}
  build:
    project: LitmosApi\LitmosApi.csproj
  before_build:
    - dotnet restore
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
